build_dir = build

[android]
enable = false
input = ArmCaveHook-Arcplugins/binaries/libcocos2dcpp.so-original
output = ArmCaveHook-Arcplugins/binaries/libcocos2dcpp.so
plugins = ArmCaveHook-Arcplugins/plugins/android

[apple]
enable = true
input = ArmCaveHook-Arcplugins/binaries/Arc-mobile.mac-catalyst
output = ArmCaveHook-Arcplugins/binaries/Arc-mobile.patched
plugins = ArmCaveHook-Arcplugins/plugins/apple
plugin_whitelist = arc_special_timing.cpp
