build_dir = build

[android]
enable = true
input = ArmCaveHook-Arcplugins/binaries/libcocos2dcpp.so
output = ArmCaveHook-Arcplugins/binaries/libcocos2dcpp.patched
plugins = ArmCaveHook-Arcplugins/plugins/android

[apple]
enable = true
input = ArmCaveHook-Arcplugins/binaries/Arc-mobile.iOS-iPadOS
output = ArmCaveHook-Arcplugins/binaries/Arc-mobile.patched
plugins = ArmCaveHook-Arcplugins/plugins/apple
